
training_features = [
    'dimuon_cos_theta_cs', 
    'dimuon_phi_cs', 
    'dimuon_rapidity', 
    'dimuon_pt', 
    'jet1_eta', 
    'jet2_eta', 
    'jet1_pt', 
    'jet2_pt', 
    'jj_dEta', 
    'jj_dPhi', 
    'jj_mass', 
    # 'mmj1_dEta', 
    # 'mmj1_dPhi',  
    'mmj_min_dEta', 
    'mmj_min_dPhi', 
    'mu1_eta', 
    'mu1_pt_over_mass', 
    'mu2_eta', 
    'mu2_pt_over_mass', 
    'zeppenfeld',
    'njets',
    'year',
]
# V2_UL_Apr09_2025_DyTtStVvEwkGghVbf_allOtherParamsOn_ScaleWgt0_75

training_samples = {
        "background": [ # full mc
            # "dy_M-100To200", 
            # "dy_M-100To200_MiNNLO",
            "dyTo2Mu_M-50_aMCatNLO",
            "dyTo2L_M-50_incl",
            # "dy_m105_160_amc",
            # "dy_m100_200_UL",
            "ttjets_dl",
            "ttjets_sl",
            "ttjets_fh",
            "st_tw_top",
            "st_tw_antitop",
            # "st_t_top",
            # "st_t_antitop",
            "ww_2l2nu",
            "wz_1l1nu2q",
            "wz_2l2q",
            "wz_3lnu",
            "zz",
            # "www",
            # "wwz",
            # "wzz",
            # "zzz",
            "ewk_mmjj_mll_105_160",
            # "ewk_mmjj",
            # "ewk_lljj",
        ],
        # "background": [ # test
        #     # "dyTo2Mu_M-50_aMCatNLO",
        #     "dyTo2L_M-50_incl",
        #     # "dy_m105_160_amc",
        #     # "dy_m100_200_UL",
        # ],
        "signal": [
            "ggh_powhegPS", 
            # "vbf_powheg_dipole", # adding vbf only makes BDT concentrate on vbf for some reason
            # "vbf_aMCatNLO", 
            "vbf_powheg*", 
        ], # copperheadV2
        # ],
        
        #"ignore": [
        #    "tttj",
        #    "tttt",
        #    "tttw",
        #    "ttwj",
        #    "ttww",
        #   "ttz",
        #    "st_s",
        #    "st_t_antitop",
        #    "st_tw_top",
        #    "st_tw_antitop",
        #    "zz_2l2q",
        #],
    }
